hmrc/vat-subscription

app/uk/gov/hmrc/vatsubscription/services/SignUpSubmissionService.scala, it/uk/gov/hmrc/vatsubscription/controllers/SignUpSubmissionControllerISpec.scala, test/uk/gov/hmrc/vatsubscription/service/SignUpSubmissionServiceSpec.scala
Reverts hmrc/vat-subscription#66
=> Revert "removed the call to tax enrolement for the agent journey"

app/uk/gov/hmrc/vatsubscription/config/AppConfig.scala, conf/application.conf, project/AppDependencies.scala
App Config Base PR:
https://github.com/hmrc/app-config-base/pull/303
=> [BTAT-3046] Removed ReactiveMongo as now unused.

app/uk/gov/hmrc/vatsubscription/models/post/PPOBAddressPost.scala, it/uk/gov/hmrc/vatsubscription/controllers/UpdateVatCustomerDetailsControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/helpers/IntegrationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/PPOBTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/post/PPOBAddressPostSpec.scala
Associated frontend PR:
https://github.com/hmrc/manage-vat-subscription-frontend/pull/183
=> [BTAT-3522] Country code is mandatory for API1365

app/uk/gov/hmrc/vatsubscription/connectors/GetVatCustomerInformationConnector.scala, app/uk/gov/hmrc/vatsubscription/controllers/RequestDeregistrationController.scala, app/uk/gov/hmrc/vatsubscription/controllers/UpdatePPOBController.scala, app/uk/gov/hmrc/vatsubscription/controllers/UpdateReturnPeriodController.scala, app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/UpdateVatSubscription.scala, app/uk/gov/hmrc/vatsubscription/services/RequestDeregistrationService.scala, app/uk/gov/hmrc/vatsubscription/services/UpdatePPOBService.scala, app/uk/gov/hmrc/vatsubscription/services/UpdateReturnPeriodService.scala, app/uk/gov/hmrc/vatsubscription/services/VatCustomerDetailsRetrievalService.scala, it/uk/gov/hmrc/vatsubscription/controllers/RequestDeregistrationControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/controllers/UpdatePPOBControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/controllers/UpdateReturnPeriodControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/helpers/IntegrationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/connectors/UpdateVatSubscriptionConnectorSpec.scala, test/uk/gov/hmrc/vatsubscription/controllers/RequestDeregistrationControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/controllers/UpdatePPOBControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/controllers/UpdateReturnPeriodControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerDetailsTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/UpdateVatSubscriptionTestConstants.scala, test/uk/gov/hmrc/vatsubscription/service/RequestDeregistrationServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdatePPOBServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdateReturnPeriodServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/VatCompanyDetailsRetrievalServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/mocks/MockDeregistrationRequestService.scala, test/uk/gov/hmrc/vatsubscription/service/mocks/MockUpdatePPOBService.scala, test/uk/gov/hmrc/vatsubscription/service/mocks/MockUpdateReturnPeriodService.scala, test/uk/gov/hmrc/vatsubscription/service/mocks/MockVatCustomerDetailsRetrievalService.scala
https://github.com/hmrc/vat-subscription/pull/141
=>  [BTAT-4049] updated to retrieve welshIndicator before submitting 

app/uk/gov/hmrc/vatsubscription/config/featureSwitch/Api1363VersionFeature.scala, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/FeatureSwitchModel.scala, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/Features.scala, app/uk/gov/hmrc/vatsubscription/testonly/controllers/FeatureSwitchController.scala, build.sbt, conf/application.conf, test/assets/TestUtil.scala, test/uk/gov/hmrc/vatsubscription/testOnly/controllers/FeatureSwitchControllerSpec.scala
Here are the app-config prs: 
* https://github.com/hmrc/app-config-base/pull/1679
* https://github.com/hmrc/app-config-production/pull/2798
Please merge them before this one
=> BTAT-5269 Refactored API1363 feature switch to match API1365 feature switch

app/uk/gov/hmrc/vatsubscription/config/featureSwitch/BaseFeature.scala, app/uk/gov/hmrc/vatsubscription/connectors/GetVatCustomerInformationConnector.scala, app/uk/gov/hmrc/vatsubscription/controllers/MicroserviceBaseController.scala, app/uk/gov/hmrc/vatsubscription/controllers/RequestDeregistrationController.scala, app/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsController.scala, app/uk/gov/hmrc/vatsubscription/controllers/UpdateReturnPeriodController.scala, app/uk/gov/hmrc/vatsubscription/httpparsers/UpdateVatSubscriptionHttpParser.scala, app/uk/gov/hmrc/vatsubscription/models/BankDetails.scala, app/uk/gov/hmrc/vatsubscription/models/VatKnownFacts.scala, build.sbt, project/plugins.sbt, scalastyle-config.xml, test/uk/gov/hmrc/vatsubscription/connectors/mocks/MockGetVatCustomerInformationConnector.scala
Also fixed some scalastyle warnings
=> Added logging of correlation ID and body of error responses

app/uk/gov/hmrc/vatsubscription/models/PendingChanges.scala, app/uk/gov/hmrc/vatsubscription/models/VatCustomerInformation.scala, it/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/helpers/IntegrationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/PendingChangesSpec.scala
I've tested this change against the recent data/schema updates to both change-vat-acceptance-tests and change-vat-details-acceptance-tests, and both tests packs have passed.
=> BTAT-6023 Added mandation status section to PendingChanges model

app/uk/gov/hmrc/vatsubscription/config/featureSwitch/FeatureSwitchModel.scala, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/Features.scala, app/uk/gov/hmrc/vatsubscription/connectors/GetVatCustomerInformationConnector.scala, app/uk/gov/hmrc/vatsubscription/models/PendingChanges.scala, app/uk/gov/hmrc/vatsubscription/models/ReturnPeriod.scala, app/uk/gov/hmrc/vatsubscription/models/VatCustomerInformation.scala, app/uk/gov/hmrc/vatsubscription/testonly/controllers/FeatureSwitchController.scala, build.sbt, conf/application.conf, test/assets/TestUtil.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/ReturnPeriodTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/PendingChangesSpec.scala, test/uk/gov/hmrc/vatsubscription/models/ReturnPeriodSpec.scala, test/uk/gov/hmrc/vatsubscription/models/VatCustomerInformationSpec.scala, test/uk/gov/hmrc/vatsubscription/testOnly/controllers/FeatureSwitchControllerSpec.scala
=> [BTAT-6825] - added annual accounting feature switch and edited filter for returnPeriod

app/uk/gov/hmrc/vatsubscription/models/VatCustomerInformation.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/VatCustomerInformationSpec.scala
=> Updated ManageAccountWrites to return contact numbers

app/uk/gov/hmrc/vatsubscription/models/VatCustomerInformation.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala
* [ y] Branch is rebased with master
* [n ] Added Unit Tests for changed functionality
* [y Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [y] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [y] Ran Acceptance tests as per the story. If any query ping in group slack and confirm the AT's repo
* [ n] Ran Performance tests as per the story. If any query ping in group slack and confirm the PT's repo
=> corrected landline field name to work with BTA

.github/pull_request_template, README.md, app/uk/gov/hmrc/vatsubscription/models/ChangeIndicators.scala, it/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/ChangeIndicatorsSpec.scala
=> Added annualAccounting to ChangeIndicators model and parser

app/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsController.scala
=> Log change indicator

README.md, app/uk/gov/hmrc/vatsubscription/config/AppConfig.scala, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/FeatureSwitchModel.scala, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/Features.scala, app/uk/gov/hmrc/vatsubscription/testonly/controllers/FeatureSwitchController.scala, conf/application.conf, test/assets/TestUtil.scala, test/uk/gov/hmrc/vatsubscription/testOnly/controllers/FeatureSwitchControllerSpec.scala
=> BTAT-7113 Removed stubDes Feature switch

app/uk/gov/hmrc/vatsubscription/models/VatKnownFacts.scala, app/uk/gov/hmrc/vatsubscription/services/VatKnownFactsRetrievalService.scala, it/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatKnownFactsControllerISpec.scala, test/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatKnownFactsControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/VatKnownFactsTestConstants.scala, test/uk/gov/hmrc/vatsubscription/service/VatKnownFactsRetrievalServiceSpec.scala
=> SAR-4781 - Pass overseas flag through on Known Facts API

app/uk/gov/hmrc/vatsubscription/models/PendingChanges.scala, app/uk/gov/hmrc/vatsubscription/models/ReturnPeriod.scala, app/uk/gov/hmrc/vatsubscription/models/TaxPeriod.scala, it/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, project/plugins.sbt, test/uk/gov/hmrc/vatsubscription/controllers/UpdateReturnPeriodControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/UpdateVatSubscriptionTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/PendingChangesSpec.scala, test/uk/gov/hmrc/vatsubscription/models/ReturnPeriodSpec.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/UpdatedReturnPeriodSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdateReturnPeriodServiceSpec.scala
=> BTAT-7255 Updated ReturnPeriod reads/writes to account for NSTP

app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/DeregistrationReason.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/DeregistrationReasonSpec.scala
=> BTAT-7294 Added new dereg reason Zero Rated

app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/ZeroRatedExmpApplication.scala
=> removed unused imports

app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/DeregistrationInfo.scala, app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/DeregistrationReason.scala, test/uk/gov/hmrc/vatsubscription/helpers/DeregistrationInfoTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/DeregistrationInfoSpec.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/deregistration/DeregistrationReasonSpec.scala
=> BTAT-7497 Added support for ExemptOnly dereg reason

app/uk/gov/hmrc/vatsubscription/config/featureSwitch/FeatureSwitchModel.scala, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/Features.scala, app/uk/gov/hmrc/vatsubscription/models/MandationStatus.scala, app/uk/gov/hmrc/vatsubscription/models/PendingChanges.scala, app/uk/gov/hmrc/vatsubscription/models/VatCustomerInformation.scala, app/uk/gov/hmrc/vatsubscription/models/post/MandationStatusPost.scala, app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/UpdateVatSubscription.scala, app/uk/gov/hmrc/vatsubscription/testonly/controllers/FeatureSwitchController.scala, conf/application.conf, it/uk/gov/hmrc/vatsubscription/controllers/GetMandationStatusControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/uk/gov/hmrc/vatsubscription/helpers/ComponentSpecBase.scala, it/uk/gov/hmrc/vatsubscription/helpers/IntegrationTestConstants.scala, test/assets/TestUtil.scala, test/uk/gov/hmrc/vatsubscription/connectors/GetVatCustomerInformationConnectorSpec.scala, test/uk/gov/hmrc/vatsubscription/controllers/RetrieveVatCustomerDetailsControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerDetailsTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/CustomerDetailsSpec.scala, test/uk/gov/hmrc/vatsubscription/models/MandationStatusSpec.scala, test/uk/gov/hmrc/vatsubscription/models/PendingChangesSpec.scala, test/uk/gov/hmrc/vatsubscription/models/VatCustomerInformationSpec.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/UpdateVatSubscriptionSpec.scala, test/uk/gov/hmrc/vatsubscription/testOnly/controllers/FeatureSwitchControllerSpec.scala
I've had to set the feature to false for now, as defaulting it to true would cause the frontends to fail parsing the new descriptions. We could revisit this at a later time to set it to true locally and in our test environments.
Please ensure this PR is merged too: https://github.com/hmrc/app-config-production/pull/6401
=> BTAT-7742 Added newStatusIndicators feature for R17

app/uk/gov/hmrc/vatsubscription/connectors/GetVatCustomerInformationConnector.scala, project/plugins.sbt
=> Updated logging levels for handleErrorResponse

README.md, app/uk/gov/hmrc/vatsubscription/config/featureSwitch/Api1365VersionFeature.scala, conf/application.conf
Please ensure this is merged too: https://github.com/hmrc/app-config-production/pull/7444
=> BTAT-7991 Added new API1365 version for R17 pre-release

app/uk/gov/hmrc/vatsubscription/models/CommsPreference.scala, app/uk/gov/hmrc/vatsubscription/models/PendingChanges.scala, it/uk/gov/hmrc/vatsubscription/helpers/IntegrationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/CommsPreferenceModelSpec.scala
=> BTAT-8015 Fixed JSON reads for commsPreference

app/uk/gov/hmrc/vatsubscription/connectors/UpdateVatSubscriptionConnector.scala, app/uk/gov/hmrc/vatsubscription/controllers/UpdateContactPreferenceController.scala, app/uk/gov/hmrc/vatsubscription/models/CommsPreference.scala, app/uk/gov/hmrc/vatsubscription/models/PendingChanges.scala, app/uk/gov/hmrc/vatsubscription/models/VatCustomerInformation.scala, app/uk/gov/hmrc/vatsubscription/models/post/CommsPreferencePost.scala, app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/RequestedChanges.scala, app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/UpdateVatSubscription.scala, app/uk/gov/hmrc/vatsubscription/services/RequestDeregistrationService.scala, app/uk/gov/hmrc/vatsubscription/services/UpdateContactPreferenceService.scala, app/uk/gov/hmrc/vatsubscription/services/UpdateEmailService.scala, app/uk/gov/hmrc/vatsubscription/services/UpdateMandationStatusService.scala, app/uk/gov/hmrc/vatsubscription/services/UpdateReturnPeriodService.scala, conf/app.routes, conf/application.conf, it/uk/gov/hmrc/vatsubscription/controllers/UpdateContactPreferenceControllerISpec.scala, test/uk/gov/hmrc/vatsubscription/connectors/UpdateVatSubscriptionConnectorSpec.scala, test/uk/gov/hmrc/vatsubscription/controllers/UpdateContactPreferenceControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/CustomerInformationTestConstants.scala, test/uk/gov/hmrc/vatsubscription/helpers/UpdateVatSubscriptionTestConstants.scala, test/uk/gov/hmrc/vatsubscription/models/CommsPreferenceModelSpec.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/RequestedChangesSpec.scala, test/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/UpdateVatSubscriptionSpec.scala, test/uk/gov/hmrc/vatsubscription/service/RequestDeregistrationServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdateContactPreferenceServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdateEmailServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdateMandationStatusServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/UpdatePPOBServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/mocks/MockUpdateContactPreferenceService.scala
=> BTAT-7948 Added new route controller model

app/uk/gov/hmrc/vatsubscription/controllers/UpdateContactPreferenceAndEmailController.scala, app/uk/gov/hmrc/vatsubscription/models/post/CommsPreferenceEmailPost.scala, app/uk/gov/hmrc/vatsubscription/models/updateVatSubscription/request/RequestedChanges.scala, app/uk/gov/hmrc/vatsubscription/services/UpdateContactPreferenceService.scala, build.sbt, conf/app.routes, it/uk/gov/hmrc/vatsubscription/controllers/UpdateContactPreferenceAndEmailControllerISpec.scala, project/plugins.sbt, test/uk/gov/hmrc/vatsubscription/controllers/UpdateContactPreferenceAndEmailControllerSpec.scala, test/uk/gov/hmrc/vatsubscription/helpers/PPOBTestConstants.scala, test/uk/gov/hmrc/vatsubscription/service/UpdateContactPreferenceServiceSpec.scala, test/uk/gov/hmrc/vatsubscription/service/mocks/MockUpdateContactPreferenceService.scala
=> [BTAT-8066] Added route to change preference to digital and update email

app/models/PendingChanges.scala, build.sbt, it/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/helpers/IntegrationTestConstants.scala, project/build.properties, project/plugins.sbt, run.sh, test/helpers/CustomerInformationTestConstants.scala, test/models/PendingChangesSpec.scala, test/models/VatCustomerInformationSpec.scala
=> BTAT-8498 Extended PendingChanges model to read/write inflight trading name

build.sbt
=> Adding to disablePlugins(JUnitXmlReportPlugin) to fix unstable build

app/models/CustomerDetails.scala, app/models/VatCustomerInformation.scala, app/services/VatCustomerDetailsRetrievalService.scala, it/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/helpers/IntegrationTestConstants.scala, test/controllers/RetrieveVatCustomerDetailsControllerSpec.scala, test/helpers/CustomerDetailsTestConstants.scala, test/helpers/CustomerInformationTestConstants.scala, test/service/MandationStatusServiceSpec.scala
=> BTAT-8725 Updated JSON reads/writes to support nameIsReadOnly field

app/services/VatKnownFactsRetrievalService.scala, it/controllers/RetrieveVatKnownFactsControllerISpec.scala, test/controllers/RetrieveVatKnownFactsControllerSpec.scala, test/helpers/CustomerInformationTestConstants.scala, test/helpers/PPOBTestConstants.scala, test/helpers/VatKnownFactsTestConstants.scala
=> SAR-6801 - Make postcode optional on VAT known facts call

app/controllers/UpdateOrganisationDetailsController.scala, app/models/TradingName.scala, app/models/updateVatSubscription/request/RequestedChanges.scala, app/models/updateVatSubscription/request/UpdateVatSubscription.scala, app/models/updateVatSubscription/request/UpdatedOrganisationDetails.scala, app/services/RequestDeregistrationService.scala, app/services/UpdateContactPreferenceService.scala, app/services/UpdateEmailService.scala, app/services/UpdateMandationStatusService.scala, app/services/UpdateOrganisationDetailsService.scala, app/services/UpdateReturnPeriodService.scala, conf/app.routes, it/controllers/UpdateOrganisationDetailsControllerISpec.scala, it/helpers/IntegrationTestConstants.scala, test/connectors/UpdateVatSubscriptionConnectorSpec.scala, test/controllers/UpdateOrganisationDetailsControllerSpec.scala, test/helpers/OrganisationDetailsTestConstants.scala, test/helpers/UpdateVatSubscriptionTestConstants.scala, test/models/updateVatSubscription/request/UpdateVatSubscriptionSpec.scala, test/models/updateVatSubscription/request/UpdatedOrganisationDetailsSpec.scala, test/service/RequestDeregistrationServiceSpec.scala, test/service/UpdateContactPreferenceServiceSpec.scala, test/service/UpdateEmailServiceSpec.scala, test/service/UpdateOrganisationDetailsServiceSpec.scala, test/service/UpdatePPOBServiceSpec.scala, test/service/UpdateReturnPeriodServiceSpec.scala, test/service/mocks/MockUpdateOrganisationDetailsService.scala
=> BTAT-8704 - added functionality to update trading name

app/models/CustomerDetails.scala, app/models/VatCustomerInformation.scala, app/services/VatCustomerDetailsRetrievalService.scala, it/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/helpers/IntegrationTestConstants.scala, test/helpers/CustomerDetailsTestConstants.scala, test/helpers/CustomerInformationTestConstants.scala
=> [BTAT-8804] - added 'isInsolvent' and 'continueToTrade'

app/models/CustomerDetails.scala, app/models/VatCustomerInformation.scala, app/models/updateVatSubscription/request/UpdatedOrganisationDetails.scala, app/services/VatCustomerDetailsRetrievalService.scala, build.sbt, it/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, it/helpers/IntegrationTestConstants.scala, test/helpers/BaseTestConstants.scala, test/helpers/CustomerDetailsTestConstants.scala, test/helpers/CustomerInformationTestConstants.scala
=> [BTAT-8803] Updated JSON reads/writes for new field

README.md
I've also removed information regarding the `/manage-account-summary` endpoint as we would prefer any other services to use the `/full-information` endpoint which has much more support. Right now it's only BTA who have that endpoint listed in their code, but I don't see any Production calls to this endpoint in the last 2 weeks, and after discussion with BTA tech lead we believe this is unused.
=> Updated readme descriptions of GET endpoints

conf/application.conf
=> [BTAT-8992] - updated deprecated JsonErrorHandler

README.md, app/models/VatCustomerInformation.scala, it/controllers/RetrieveVatCustomerDetailsControllerISpec.scala, test/helpers/CustomerDetailsTestConstants.scala, test/helpers/CustomerInformationTestConstants.scala, test/helpers/PPOBTestConstants.scala, test/models/VatCustomerInformationSpec.scala, test/services/MandationStatusServiceSpec.scala, test/services/UpdateContactPreferenceServiceSpec.scala, test/services/VatCompanyDetailsRetrievalServiceSpec.scala, test/services/VatKnownFactsRetrievalServiceSpec.scala
I had to touch a few unrelated bits of test data because I have made changes to some existing "minimum" models & JSON to be more accurate with respect to the DES spec's actual minimum JSON returned.
=> BTAT-9144 Updated primaryMainCode to be optional to match DES spec

app/connectors/GetVatCustomerInformationConnector.scala, app/connectors/UpdateVatSubscriptionConnector.scala, build.sbt, it/helpers/servicemocks/AuthStub.scala, project/plugins.sbt, test/controllers/UpdateOrganisationDetailsControllerSpec.scala, test/services/RequestDeregistrationServiceSpec.scala, test/services/UpdateEmailServiceSpec.scala, test/services/UpdateMandationStatusServiceSpec.scala, test/services/UpdatePPOBServiceSpec.scala, test/services/UpdateReturnPeriodServiceSpec.scala, test/services/VatCompanyDetailsRetrievalServiceSpec.scala, test/services/VatKnownFactsRetrievalServiceSpec.scala
=> [BTAT-9274] Upgrade bootstrap-backend-play

README.md, app/config/featureSwitch/FeatureSwitchModel.scala, app/config/featureSwitch/Features.scala, app/models/PendingChanges.scala, app/models/ReturnPeriod.scala, app/models/VatCustomerInformation.scala, app/testonly/controllers/FeatureSwitchController.scala, conf/application.conf, test/helpers/TestUtil.scala, test/models/ReturnPeriodSpec.scala, test/models/VatCustomerInformationSpec.scala, test/testOnly/controllers/FeatureSwitchControllerSpec.scala
=> Btat 9904 Removed enableAnnualAccounting feature switch

.gitignore, build.sbt, project/build.properties, project/plugins.sbt
=> [BTAT-10231] - Updated dependencies, sbt version and removed unused settings

app/models/ReturnPeriod.scala, it/controllers/UpdateReturnPeriodControllerISpec.scala
=> [BTAT-10231] - Update return period to be optional

build.sbt, conf/application-json-logger.xml, conf/application.conf, project/build.properties, project/plugins.sbt
=> [BTAT-10867] - Updated bootstrap and relevant dependencies

build.sbt, it/helpers/ComponentSpecBase.scala, project/plugins.sbt, test/controllers/MandationStatusControllerSpec.scala, test/controllers/RetrieveVatKnownFactsControllerSpec.scala
=> [BTAT-11039] - Updated to scala 2.13

README.md
=> [BTAT-11171] Update readme

app/connectors/GetVatCustomerInformationConnector.scala, app/connectors/UpdateVatSubscriptionConnector.scala, test/connectors/GetVatCustomerInformationConnectorSpec.scala, test/connectors/UpdateVatSubscriptionConnectorSpec.scala, test/helpers/MockHttpClient.scala
Please also merge: https://github.com/hmrc/app-config-production/pull/17945
=> BTAT-11516 Added HttpException recovery to connectors

README.md
=> BTAT-11557 Adding contracts for missing end points

app/models/PartyType.scala
To address recent exceptions observed in Production
=> Added support for partyType 57

app/config/Features.scala, app/services/UpdatePPOBService.scala, conf/application.conf
=> [DL-14470] Fixing config for new feature switch for phone number regex

app/controllers/RetrieveVatCustomerDetailsController.scala, app/httpparsers/GetVatCustomerInformationHttpParser.scala, app/models/VatCustomerInformation.scala
=> DL-15709: Added response
